package consts

var (
	// ordered list of addresses as they would be generated by the flow emulator
	// todo: this is obviously not scalable and should be replaced with the logic to generate
	// these addresses
	EMULATOR_ADDRESS_ORDER = []string{
		"0xf8d6e0586b0a20c7",
		"0x01cf0e2f2f715450",
		"0x179b6b1cb6755e31",
		"0xf3fcd2c1a78f5eee",
		"0xe03daebed8ca0615",
		"0x45a1763c93006ca",
		"0x120e725050340cab",
		"0xf669cb8d41ce0c74",
		"0x192440c99cb17282",
		"0xfd43f9148d4b725d",
		// ...
	}
)
